name = "CircuitSimulator"
uuid = "11c13930-7915-11e8-388a-47fcf8988b4a"
authors = ["Chris Stook <chris@chrisstook.com>"]
version = "0.1.0"

[deps]
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
