name = "CircuitSimulator"
uuid = "11c13930-7915-11e8-388a-47fcf8988b4a"
authors = ["Chris Stook <chris@chrisstook.com>"]
version = "0.1.0"

[deps]
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
